name: data-aggregation-service
services:
    db:
        image: postgres
        container_name: postgres
        restart: unless-stopped
        shm_size: 127mb
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: admindb
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    
    rabbitmq:
        image: rabbitmq:4-management
        container_name: rabbitmq
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
    
    # https://docs.confluent.io/platform/current/installation/docker/config-reference.html
    # https://hub.docker.com/r/apache/kafka
    # This did not work probably because Im overriding some important env properties
    # kafka0:
    #     image: apache/kafka:latest
    #     container_name: kafka0
    #     ports:
    #         - "9092:9092"
    #         - "9093:9093"
    #     environment:
    #         KAFKA_NODE_ID: 1
    #         # usually a kafka server will act as only one role
    #         # this is only required in KRaft mode
    #         KAFKA_PROCESS_ROLES: broker, controller
    #         KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    #         KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka0:9093

    #         # each port kafka will use as broker and as a controller
    #         KAFKA_LISTENERS: INTERNAL://kafka0:29092,EXTERNAL://kafka0:9092,CONTROLLER://kafka0:9093

    #         KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka0:29092,EXTERNAL://localhost:9092
            
    #         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

    #         # default listener which other brokers will use to connect to this one
    #         KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

    #         # Replication Factor for each topic across brokers (only one broker currently)
    #         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    #         KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    #         KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #         KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            
    #         # this changes the number of partitions within each topic
    #         KAFKA_NUM_PARTITIONS: 3
    
    kafka1:
        image: apache/kafka:latest
        container_name: kafka1
        ports:
            - "9092:9092"


volumes:
    postgres_data: